<a href="https://colab.research.google.com/github/mohammed2711111/Last_Project-Portfolio-/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
model=keras.Sequential([
      layers.Dense(512, activation="relu"),
      layers.Dense(10, activation="softmax")
])

In [ ]:
model.compile(optimizer="rmsprop",
            loss="sparse_categorical_corssentropy",
            metrics=["accuracy"])

In [ ]:
train_images = train_images.reshape((60000 , 28*28))
train_images=train_images.astype("float32")/255
test_images=test_images.reshape((10000,28 * 28))
test_images=test_images.astype("float32")/255 

In [ ]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5


ValueError: ignored

In [ ]:
test_digits=test_images[0:10]
predictions=model.predict(test_digits)
predictions[0]

array([0.11350341, 0.07260302, 0.11097357, 0.09532104, 0.07448577,
       0.11324685, 0.12109821, 0.09248234, 0.12257802, 0.08370773],
      dtype=float32)

In [ ]:
predictions[0].argmax()

8

In [ ]:
predictions[0][7]

0.09248234

In [ ]:
test_labels[0]

7

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

ValueError: ignored